export const countries = [
  'Belgium',
  'France',
  'Luxembourg',
  'Germany',
  'The Netherlands',
  'Spain',
  'Italy',
  'Greece',
  'Portugal',
  'Austria',
  'Denmark',
  'Norway',
  'Sweden',
  'Finland',
  'Ireland',
  'Poland',
  'Estonia',
  'Latvia',
  'Lithuania',
  'Slovak Republic',
  'United Kingdom',
  'Croatia',
  'Serbia',
  'Bosnia and Herzegovina',
  'Bulgaria',
  'Czech Republic',
  'Hungary',
  'Slovenia',
  'Switzerland'
];
